"""Init

Revision ID: fe5d9c01c14e
Revises: b777d9ef9c17
Create Date: 2024-06-08 15:11:41.099664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe5d9c01c14e'
down_revision: Union[str, None] = 'b777d9ef9c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=False))
    op.drop_column('todos', 'compiled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('compiled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
